{% set version = "0.5.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mertools
  version: {{ version|replace("-", "_") }}

source:
  fn: merTools_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/merTools_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/merTools/merTools_{{ version }}.tar.gz
  sha256: 99110248bf135189db06d012f6f493c04f250527a3022a3a406dc353ac1d0ea7

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-dt
    - r-abind
    - r-arm
    - r-blme
    - r-broom
    - r-dplyr
    - r-foreach
    - r-ggplot2
    - r-lme4 >=1.1_11
    - r-mvtnorm
    - r-shiny

  run:
    - r-base
    - r-dt
    - r-abind
    - r-arm
    - r-blme
    - r-broom
    - r-dplyr
    - r-foreach
    - r-ggplot2
    - r-lme4 >=1.1_11
    - r-mvtnorm
    - r-shiny

test:
  commands:
    - $R -e "library('merTools')"  # [not win]
    - "\"%R%\" -e \"library('merTools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=merTools
  license: GPL (>= 2)
  summary: Provides methods for extracting results from mixed-effect model objects fit with the
    'lme4' package. Allows construction of prediction intervals efficiently from large
    scale linear and generalized linear mixed-effects models.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - ccwang002
