# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XfXEsZ1YKAwoY9WpHd+Utbbfqd/Ndwo8EdGArbCPSN4JGpLEAIsPLANIKN6c9rjNVcDv0vVbF6RInjOn5UYMwma2GzXv47A1xOHPjXEAuOufz0c0uecoyCAjGwjTe0lfTs4OoihPJoKxSrzQypSk9dszuo/TduXuOdCgPpq4ldbh3v+Gq0ucRANKtvRkbZk2Zk4ap3D+gZXLob/l39E5FlNpmvJXzu2P5jQl8jmpF0j4yF/Wvy+0Aw4hsdcjgERHUWrztwICFutPHP8zxPGqHUx9UESaBq40PLf6b1xDj6b0Z0iVJiCG6xpqig+8XyMEHPaeeg8VmqVnHanG43aTwyETQC4A5aLw4Z9pFZjOpJLzktVGLay6QnwhJf+Rwg//JND7+qtelOQTdkWfLBq79xGX2YE4yBMZNJFq8hG1YmMJ2+ml5AYRh9Fqrg1XhB2Qh+xGVQVNY/tm9sUrvgrbI6/CxkwgzCUaw0kcCawXcyMZidTqX+0h69SehjGQq93f3dw9LGPcLwZYJBsTUZF50+7SLrnblcJw/KWW1w71xIGSwaHmfiL008oq+fsd5LKXxAp2hA40oQFdz5wmgTQY3VE2M01r2QOkOoTmsIuus/UGmVqDBSHMpHNQQzsbIDPsaiO/K9a/6Gala49385YBSfx7QTQsMIJ0DrpoDG6iigA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
