appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XfXEsZ1YKAwoY9WpHd+Utbbfqd/Ndwo8EdGArbCPSN4JGpLEAIsPLANIKN6c9rjNVcDv0vVbF6RInjOn5UYMwma2GzXv47A1xOHPjXEAuOufz0c0uecoyCAjGwjTe0lfTs4OoihPJoKxSrzQypSk9dszuo/TduXuOdCgPpq4ldbh3v+Gq0ucRANKtvRkbZk2Zk4ap3D+gZXLob/l39E5FlNpmvJXzu2P5jQl8jmpF0j4yF/Wvy+0Aw4hsdcjgERHUWrztwICFutPHP8zxPGqHUx9UESaBq40PLf6b1xDj6b0Z0iVJiCG6xpqig+8XyMEHPaeeg8VmqVnHanG43aTwyETQC4A5aLw4Z9pFZjOpJLzktVGLay6QnwhJf+Rwg//JND7+qtelOQTdkWfLBq79xGX2YE4yBMZNJFq8hG1YmMJ2+ml5AYRh9Fqrg1XhB2Qh+xGVQVNY/tm9sUrvgrbI6/CxkwgzCUaw0kcCawXcyMZidTqX+0h69SehjGQq93f3dw9LGPcLwZYJBsTUZF50+7SLrnblcJw/KWW1w71xIGSwaHmfiL008oq+fsd5LKXxAp2hA40oQFdz5wmgTQY3VE2M01r2QOkOoTmsIuus/UGmVqDBSHMpHNQQzsbIDPsaiO/K9a/6Gala49385YBSfx7QTQsMIJ0DrpoDG6iigA=}
